version: '3.3'

services:
  mariadb:
    image: "mariadb:latest"
    container_name: dj_db
    hostname: mariadb
    env_file:
      - .env
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - coding_db:/var/lib/mysql
  domserver:
    image: "tsacoding/domserver:latest"
    container_name: dj_domserver
    ports:
      - 12345:80
    depends_on:
      - mariadb
    env_file:
      - .env
  judgehost:
    image: "tsacoding/judgehost:latest"
    container_name: dj_judgehost
    hostname: judgehost
    depends_on:
      - domserver
    env_file:
      - .env
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup

volumes:
  coding_db:
