version: '3.7'

services:
  db:
    image: "mariadb:latest"
    container_name: dj_db
    volumes:
      - coding_db:/var/lib/mysql
    env_file:
      - .env
    command: mysqld --max-connections=1000
  domserver:
    build:
      context: .
      dockerfile: domserver.Dockerfile
    container_name: dj_domserver
    ports:
      - 5000:80
    depends_on:
      - db
    env_file:
      - .env
  judgehost:
    build:
      context: .
      dockerfile: judgehost.Dockerfile
    container_name: dj_judgehost
    depends_on:
      - domserver
    env_file:
      - .env
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

volumes:
  coding_db:
