#!/bin/sh

# C++ compile wrapper-script for 'compile.sh'.
# See that script for syntax and more info.

DEST="$1" ; shift
MEMLIMIT="$1" ; shift

# Add -DONLINE_JUDGE or -DDOMJUDGE below if you want it make easier for teams
# to do local debugging.

# -x c++:     Explicitly set compile language to C++ (no object files or
#             other languages autodetected by extension)
# -std=c++20: Explicitly set C++20 mode
# -Wall:      Report all warnings
# -O2:        Level 2 optimizations (default for speed)
# -static:    Static link with all libraries
# -pipe:      Use pipes for communication between stages of compilation
g++ -x c++ -std=c++20 -Wall -O2 -static -pipe -o "$DEST" "$@"
exit $?
